from __future__ import annotations
import json
import os
from typing import Dict, List, Tuple

from services.store import REPORTS_DIR


def generate_markdown_report(report_data: Dict) -> str:
    """将报告数据转换为 Markdown 格式字符串"""
    meta = report_data.get("meta", {})
    summary = report_data.get("global_summary", "暂无总结")
    articles = report_data.get("articles", [])

    md_lines: List[str] = []
    md_lines.append(f"# 🧬 {meta.get('domain', 'RSS')} AI Daily Brief")
    md_lines.append(f"> 📅 Date: {meta.get('date')} | 📊 Passed: {meta.get('total_passed')}/{meta.get('total_raw')}\n")

    md_lines.append("## 📰 本期看点 (Executive Summary)")
    md_lines.append(summary)
    md_lines.append("\n---\n")
    md_lines.append("## 📚 精选文章 (Selected Articles)\n")

    for idx, art in enumerate(articles, 1):
        ai = art.get("ai_analysis", {})
        title_cn = ai.get("title_cn", art.get("title"))
        score = ai.get("score", 0)

        score_icon = "🌟" if score >= 9 else ("🔥" if score >= 7 else "📄")

        md_lines.append(f"### {idx}. {title_cn} {score_icon} {score}")
        md_lines.append(f"**🔗 原文链接**: [{art.get('title')}]({art.get('link')})")
        if ai.get("one_sentence"):
            md_lines.append(f"**📌 一句话看点**: {ai.get('one_sentence')}")

        kws = ai.get("keywords", [])
        if isinstance(kws, list):
            kw_text = ", ".join(kws)
        else:
            kw_text = str(kws)
        md_lines.append(f"**🏷️ 标签**: {kw_text}")
        md_lines.append(f"**📝 摘要**: {ai.get('summary', '无')}")

        if ai.get("reason"):
            md_lines.append(f"> *💡 评分依据: {ai.get('reason')}*")

        md_lines.append("\n---\n")

    md_lines.append("\n*Generated by AI RSS Flow*")
    return "\n".join(md_lines)


def load_all_reports(limit: int | None = None) -> List[Dict]:
    files = []
    if os.path.isdir(REPORTS_DIR):
        for name in os.listdir(REPORTS_DIR):
            if name.endswith(".json"):
                files.append(os.path.join(REPORTS_DIR, name))
    files.sort(key=lambda p: os.path.getmtime(p), reverse=True)

    reports: List[Dict] = []
    for p in (files[:limit] if limit else files):
        try:
            with open(p, "r", encoding="utf-8") as f:
                reports.append(json.load(f))
        except Exception:
            continue
    return reports


def aggregate_history_stats(limit: int | None = 20) -> Dict:
    """从历史报告中汇总统计（类别分布、每期文章数、总报告数等）"""
    reports = load_all_reports(limit=limit)
    category_count: Dict[str, int] = {}
    per_issue_passed: List[Tuple[str, int]] = []

    for r in reports:
        meta = r.get("meta", {})
        per_issue_passed.append((meta.get("date", ""), int(meta.get("total_passed", 0))))
        for art in r.get("articles", []):
            cat = art.get("ai_analysis", {}).get("category", "OTHER")
            category_count[cat] = category_count.get(cat, 0) + 1

    total_reports = len(reports)
    return {
        "category_count": category_count,
        "per_issue_passed": per_issue_passed,
        "total_reports": total_reports,
    }
